CC = c++


namespace:
		$(CC) namespace.cpp && ./a.out

cout:
		$(CC) cout.cpp && ./a.out

class:
		$(CC) SampleClass.cpp Samplemain.cpp && ./a.out

member:
		$(CC) MemberClass.cpp Membermain.cpp && ./a.out

initlist:
		$(CC) InitListClass.cpp InitListmain.cpp && ./a.out
